title: 'Dr. Nakamoto'
description: "Insane inventor, creating beyond imagination."
baseurl: "/drnakamoto"
url: "https://drnakamoto.github.io/"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: hacker

footer: 'follow <a href="https://twitter.com/">twitter</a> <a href="https://twitter.com/">opensea</a>'

# Build settings
markdown: kramdown
remote_theme: jekyll-theme-console
